#!/bin/sh

SIGNTOOL="SignatureTool.jar"
#SIGNTOOL="SignatureToolRunner.jar"
#COD="BBB.obf.cod"
COD="BBB.cod"

RES=
RIM="/Users/zeno/Projects/RCSBlackBerry/Sources/Workspace/RCSBlackBerry/sign"
#VER="4.5.0"
VER="./"
KEYSDIR="Keys"
PWD="KUZ93HQ1"

echo "Sign"

echo java -jar $RIM/$SIGNTOOL -p $PWD -a -c $1

 
